-- Script de creación de tablas para Supabase - Good Style

-- 1. Tabla de Productos
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  "numericId" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  "categoryDisplay" TEXT NOT NULL,
  price NUMERIC NOT NULL,
  "originalPrice" NUMERIC,
  image TEXT NOT NULL,
  images JSONB NOT NULL DEFAULT '[]'::jsonb,
  sizes JSONB NOT NULL DEFAULT '[]'::jsonb,
  stock JSONB NOT NULL DEFAULT '{}'::jsonb,
  rating NUMERIC NOT NULL DEFAULT 5,
  "reviewsCount" BIGINT NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  features JSONB NOT NULL DEFAULT '[]'::jsonb,
  badge TEXT DEFAULT '',
  slug TEXT NOT NULL,
  "isNew" BOOLEAN DEFAULT false,
  "isSale" BOOLEAN DEFAULT false,
  "isBestSeller" BOOLEAN DEFAULT false,
  sku TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Pedidos
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  "customerName" TEXT NOT NULL,
  "customerPhone" TEXT NOT NULL,
  "customerEmail" TEXT NOT NULL,
  "shippingMethod" TEXT NOT NULL,
  "paymentMethod" TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total NUMERIC NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Reseñas
CREATE TABLE IF NOT EXISTS public.reviews (
  id TEXT PRIMARY KEY,
  "productId" TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  location TEXT NOT NULL,
  rating NUMERIC NOT NULL DEFAULT 5,
  date TEXT NOT NULL,
  comment TEXT NOT NULL,
  verified BOOLEAN DEFAULT false
);

-- 4. Tabla de Cupones
CREATE TABLE IF NOT EXISTS public.coupons (
  code TEXT PRIMARY KEY,
  "discountPercentage" NUMERIC NOT NULL,
  active BOOLEAN DEFAULT true
);

-- 5. Tabla de Configuración (Settings)
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Deshabilitar Row Level Security (RLS) en todas las tablas para permitir lectura/escritura pública directa mediante la clave Anon.
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
